# -*- coding: utf-8 -*-
#/#############################################################################
#
#    OpenEduCat Inc
#    Copyright (C) 2004-TODAY OpenEduCat Inc(<http://www.OpenEduCat Inc.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#/#############################################################################
from osv import osv, fields

class op_marksheet_register(osv.osv):
    _name = 'op.marksheet.register'

    _columns = {
            'exam_session_id': fields.many2one('op.exam.session', string='Exam', required=True),
            'marksheet_line': fields.one2many('op.marksheet.line', 'marksheet_reg_id', string='Marksheets'),
            'generated_date': fields.date(string='Generated Date', required=True),
            'generated_by': fields.many2one('res.users', string='Generated By', required=True),
            'status': fields.selection([('d','Draft'),('v','Validated'),('c','Cancelled')], string='Status', required=True),
            'total_pass': fields.float(string='Total Pass'),
            'total_failed': fields.float(string='Total Fail'),
            'name': fields.char(size=256, string='Marksheet Register', required=True),
    }

op_marksheet_register()
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
