apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openemis

resources:
  - namespace.yaml
  - postgres.yaml
  - openemis.yaml

# Override the openEMIS container image tag here (or via --set-image at deploy time)
images:
  - name: openemis
    newName: openemis
    newTag: latest
